### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by enricofico08** [bobbingwide/oik-weight-zone-shipping#29] opened 2020-12-27 18:34 UTC
Hi. I have updated to the latest version (0.2.1)

i have a problem on the line 200 of  class-oik-weight-zone-shipping-multi-rate.php but i can't solve it.
It's seems perfect see the new php files. I can't focus the problem.
Can u halp me, pleae???
Everythings works withthe previous version... :(

**Comment by bobbingwide** [comment] 2020-12-29 10:58
Hi, line 200 tries to find out how many items there are in the `$terms` variable, which is expected to be an array of the taxonomy terms for `product_shipping_class`.  It should work when the array is empty.
It would appear that the value being passed for `$terms` is not an array.  
It may be null or even an instance of a WordPress error ( `WP_error` ).

Questions:
1. Are you able to find out what the value is?   
2. What version of WordPress and WooCommerce are you using. 
3. What version of PHP?

I haven't been able to reproduce the problem.

Would you be able to change the code to: 
```
if ( $terms && count( $terms ) ) {
```

and see if that fixes it?

**Comment by bobbingwide** [comment] 2020-12-29 15:01
> I haven't been able to reproduce the problem

...  I did have the same problem with oik-weight-zone-shipping-pro. Unfortunately I didn't debug it at the time and have been unable to reproduce it with the latest version of WooCommerce.

**Comment by bobbingwide** [comment] 2020-12-29 17:56
### Problem determiniation 

The latest status is that I've been unable to reproduce the problem with the latest version of WooCommerce.
However, it is possible to improve the code to cater for the possible results from `get_terms()`.
Also, since WordPress 4.5.0 the parameters to `get_terms()` have changed. 
There isn't a deprecated message being produced but I should change the code anyway. 


BTW: This is a copy of the issue's original title.

Warning: count(): Parameter must be an array or an object that implements Countable in  
in /web/htdocs/www.mydomain.ext/home/wp-content/plugins/oik-weight-zone-shipping/class-oik-weight-zone-shipping-multi-rate.php on line 200

**Comment by bobbingwide** [comment] 2023-08-08 08:43
Delivered in v0.2.2. Closing therefore

**Closed as completed by bobbingwide** 2023-08-08 08:43 UTC
Labels: bug
